[package]
name = "rtdlib"
version = "99.99.99"
authors = ["fewensa <fewensa@protonmail.com>"]
description = "TDLib for rust"
homepage = "https://github.com/fewensa/rtdlib"
repository = "https://github.com/fewensa/rtdlib"
license = "MIT"
keywords = ["tdlib", "telegram", "bindings"]
categories = ["api-bindings"]
include = [
  "Cargo.toml",
  "**/*.rs",
  "README.md",
  "LICENSE"
]
readme = "README.md"
edition = "2018"

[dependencies]
libc = "0.2"

serde = "1"
serde_derive = "1"
serde_json = "1"
typetag = "0.1"

#strum = "0.15"
#strum_macros = "0.15"

text-reader = "0.2"
rstring-builder = "0.1"

[build-dependencies]
